complete -c box -s e -l ephemeral -l tmp -d 'Pure in-memory RAM mode (tmpfs)'
complete -c box -l secure -d 'Clear inherited env and hide broad /run and /var mounts'
complete -c box -l dry-run -d 'Print sandbox plan without starting it'
complete -c box -s n -l offline -l no-net -d 'Completely cut off network access'
complete -c box -l net -x -a 'host none proxy proxy:1819' -d 'Network mode'
complete -c box -s P -l proxy -x -d 'Set local SOCKS5 proxy environment (default: 1819)'
complete -c box -s g -l gpu -d 'Grant access to Nvidia GPU and CUDA devices'
complete -c box -s s -l share -r -d 'Share host path Read-Only (repeatable)'
complete -c box -s S -l share-rw -r -d 'Share host path Read-Write (repeatable)'
complete -c box -s w -l workdir -r -d 'Explicit workspace directory (default: .box/work)'
complete -c box -l clear-env -d 'Start with a clean environment'
complete -c box -l env -x -d 'Set KEY=VALUE inside Box'
complete -c box -l env-pass -x -d 'Pass one host variable explicitly'
complete -c box -l profile -x -d 'Load trusted profile from ~/.config/box/profiles'
complete -c box -l profiles -d 'List trusted profiles'
complete -c box -l path -d 'Print local .box path'
complete -c box -l status -d 'Show local Box storage status'
complete -c box -l mem -x -d 'Cap RAM usage via cgroups (e.g. --mem 4G)'
complete -c box -l cpu -x -d 'Cap CPU quota via cgroups (e.g. --cpu 200%)'
complete -c box -l clean -d 'Wipe local .box storage for current project'
complete -c box -l inspect -d 'Trace file access with strace'
complete -c box -s h -l help -d 'Show help manual'
