# ==============================================================================
# USER: amir
# ==============================================================================
# The NixOS-side user definition is generated by `mkUser` (see lib/mkUser.nix).
# Home-manager modules for this user are imported in ./home.nix — the user
# stays fully in control of which software it gets, independent of this file.
import ../../lib/mkUser.nix {
  name = "amir";
  isAdmin = true; # wheel — works with sudo-rs execWheelOnly
  extraGroups = [
    "podman" # system Podman access (see modules/nixos/virtualisation.nix)
  ];
}
